### Get all currencies - 200 ok
GET http://localhost:8080/currency_exchanger_war/currencies
Accept: application/json

### Add new currency - 201 creaated
POST http://localhost:8080/currency_exchanger_war/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Georgian Lari &
code=GEL &
sign=₾

### Add new currency - 400 bad request
### Invalid or missing parameters
POST http://localhost:8080/currency_exchanger_war/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Georgian Lari &
code= &
sign=₾


### Add new currency - 409 conflict
### Currency already exist in the database
POST http://localhost:8080/currency_exchanger_war/currencies

name=US Dollar &
code=USD &
sign=$

### Get currency by code - 200 Ok
GET http://localhost:8080/currency_exchanger_war/currency/USD
Accept: application/json

### Get currency by code - 400 Bad Request
### Invalid currecny code format
GET http://localhost:8080/currency_exchanger_war/currency/Usd
Accept: application/json

### Get currency by code - 404 Not Found
### Requested currency not found in the database
GET http://localhost:8080/currency_exchanger_war/currency/PLN
Accept: application/json