### Get exchange rate - 200 Ok
GET http://localhost:8080/currency_exchanger_war/exchangeRate/USDEUR
Accept: application/json

### Get exchange rate - 400 bad request
### Invalid or missing currency codes in the path
GET http://localhost:8080/currency_exchanger_war/exchangeRate/US3EUR
Accept: application/json

### Get exchange rate - 404 not found
### Invalid or missing currency codes in the path
GET http://localhost:8080/currency_exchanger_war/exchangeRate/PLNEUR
Accept: application/json

### Patch exchange rate - 200 Ok
PATCH http://localhost:8080/currency_exchanger_war/exchangeRate/USDEUR
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=1.3

### Patch exchange rate - 400 Bad Request
### Invalid or missing rate parameter
PATCH http://localhost:8080/currency_exchanger_war/exchangeRate/USDEUR
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=qwe

### Patch exchange rate - 404 Not Found
### Exchange rate for currencies is not present in the database
PATCH http://localhost:8080/currency_exchanger_war/exchangeRate/PLNEUR
Accept: application/json
Content-Type: application/x-www-form-urlencoded

rate=1.32